# Generated by Django 2.2.7 on 2021-05-14 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('region', models.CharField(choices=[('Брестская область', 'Брестская область'), ('Витебская область', 'Витебская область'), ('Гомельская область', 'Гомельская область'), ('Гродненская область', 'Гродненская область'), ('Минская область', 'Минская область'), ('Минск', 'Минск')], max_length=30)),
                ('street', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FilialGadget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('available', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operators.Filial')),
                ('gadget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gadgets.Gadget')),
            ],
        ),
    ]
