# Generated by Django 2.2.7 on 2021-05-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_filialtariff_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldgadget',
            name='amount',
            field=models.IntegerField(verbose_name='Amounts'),
        ),
    ]
