# Generated by Django 2.2.7 on 2021-05-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0005_auto_20210519_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='filialgadget',
            options={'verbose_name_plural': 'Гаджеты в филиалах'},
        ),
        migrations.AlterModelOptions(
            name='soldgadget',
            options={'verbose_name_plural': 'Проданные гаджеты'},
        ),
    ]
