# Generated by Django 2.2.7 on 2021-05-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0006_auto_20210520_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filialgadget',
            old_name='price',
            new_name='sale_price',
        ),
        migrations.AddField(
            model_name='filialgadget',
            name='stock_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
