# Generated by Django 2.2.7 on 2021-05-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0007_auto_20210523_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldgadget',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
