# Generated by Django 2.2.7 on 2021-05-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('operators', '0005_auto_20210519_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectedTv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tvs', to='clients.Client')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tvs', to='operators.Filial')),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connected_tvs', to='services.Tv')),
            ],
            options={
                'verbose_name_plural': 'Подключенные телевидения',
            },
        ),
        migrations.CreateModel(
            name='ConnectedTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to='clients.Client')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to='operators.Filial')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connected_tariffs', to='services.Tariff')),
            ],
            options={
                'verbose_name_plural': 'Подключенные тарифы',
            },
        ),
    ]
