# Generated by Django 2.2.7 on 2021-05-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='tv',
            options={'verbose_name_plural': 'Телевидения'},
        ),
    ]
