# Generated by Django 2.2.7 on 2021-05-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20210520_1510'),
        ('operators', '0006_auto_20210520_1510'),
        ('services', '0002_auto_20210520_1510'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connectedtariff',
            unique_together={('filial', 'tariff', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='connectedtv',
            unique_together={('filial', 'tv', 'client')},
        ),
    ]
