# Generated by Django 2.2.7 on 2021-05-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20210521_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedtariff',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='connectedtv',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
