# Generated by Django 2.2.7 on 2021-05-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20210521_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedtariff',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='connectedtv',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
