# Generated by Django 2.2.7 on 2021-05-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210522_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectedtariff',
            name='date',
        ),
        migrations.RemoveField(
            model_name='connectedtv',
            name='date',
        ),
    ]
