# Generated by Django 2.2.7 on 2021-05-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20210522_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedtariff',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='connectedtv',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
