# Generated by Django 2.2.7 on 2021-05-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210519_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Клиенты'},
        ),
    ]
