# Generated by Django 2.2.7 on 2021-05-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='gadget',
            options={'verbose_name_plural': 'Гаджеты'},
        ),
        migrations.AlterField(
            model_name='gadget',
            name='type',
            field=models.CharField(choices=[('Ноутбук', 'Ноутбук'), ('Смартфон', 'Смартфон'), ('Планшет', 'Планшет'), ('Наушники', 'Наушники'), ('Умные часы', 'Умные часы'), ('Портативная колонка', 'Портативная колонка')], max_length=20),
        ),
    ]
