# Generated by Django 2.2.7 on 2021-05-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_auto_20210520_1510'),
        ('operators', '0006_auto_20210520_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('Подключено телевидение', 'Подключено телевидение'), ('Подключен тариф', 'Подключен тариф')], max_length=50, unique=True)),
                ('yesterday', models.PositiveIntegerField(blank=True, null=True)),
                ('today', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_week', models.PositiveIntegerField(blank=True, null=True)),
                ('current_week', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_month', models.PositiveIntegerField(blank=True, null=True)),
                ('current_month', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Accounting',
            },
        ),
        migrations.CreateModel(
            name='AcccuntingOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('operation', models.CharField(choices=[('Подключено телевидение', 'Подключено телевидение'), ('Подключен тариф', 'Подключен тариф')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gadget', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_operations', to='operators.SoldGadget')),
                ('tariff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_operations', to='services.ConnectedTariff')),
                ('tv', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_operations', to='services.Tv')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
