# Generated by Django 2.2.7 on 2021-05-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acccuntingoperation',
            old_name='amount',
            new_name='price',
        ),
    ]
