# Generated by Django 2.2.7 on 2021-05-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0006_auto_20210520_1510'),
        ('services', '0002_auto_20210520_1510'),
        ('accounting', '0003_auto_20210520_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcccuntingOperation',
            new_name='AccountingOperation',
        ),
    ]
