# Generated by Django 2.2.7 on 2021-05-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20210520_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounting',
            options={'verbose_name_plural': 'Бухгалтерия'},
        ),
        migrations.AlterModelOptions(
            name='accountingoperation',
            options={'verbose_name_plural': 'Бухгалтерские операции'},
        ),
    ]
