# Generated by Django 2.2.7 on 2021-05-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20210521_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='operation',
            field=models.CharField(choices=[('Подключено телевидение', 'Подключено телевидение'), ('Подключен тариф', 'Подключен тариф'), ('Продан гаджет', 'Продан гаджет')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='accountingoperation',
            name='operation',
            field=models.CharField(choices=[('Подключено телевидение', 'Подключено телевидение'), ('Подключен тариф', 'Подключен тариф'), ('Продан гаджет', 'Продан гаджет')], max_length=50),
        ),
    ]
